name: Unit Tests

on:
  - push
  - pull_request

jobs:
  tests:
    strategy:
      matrix:
        version: [ '14.x', '16.x', 'lts/*' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Setup pnpm and install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: ^7.30.0
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Run Type Checks
        run: pnpm test

      - name: Run Tests
        run: pnpm test